branches:
  only:
    - 'master'
language: php
php:
  - 5.6
sudo: false
script:
  - '[ "$TRAVIS_BRANCH" == master ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && bash ./deploy.sh'
cache:
  directories:
    - output_prod
