language: php
php:
  - 5.6
sudo: false
branches:
  only:
    - master
script:
  - gem install tw
  - '[ "$TRAVIS_PULL_REQUEST" == "false" ] && bash ./deploy.sh'
cache:
  directories:
    - .sculpin
    - ~/.rvm
