language: php
php:
  - 5.6
sudo: false
script:
  - gem install tw
  - '[ "$TRAVIS_BRANCH" == master ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && bash ./deploy.sh'
cache:
  directories:
    - .sculpin
    - ~/.rbenv
